config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/book_a_rental', to: 'rentals#book_a_rental'
  get '/bookings', to: 'bookings#index'
  get '/my_email', to: 'bookings#set_my_email'
  get '/my_bookings', to: 'bookings#my_bookings'
  resources :rentals do
    resources :bookings, only: %i[new create destroy show edit update]
  end
end

app/models/booking.rb
class Booking
  include ActiveModel::Conversion
  extend  ActiveModel::Naming
  attr_accessor :id,
                :rental_id,
                :client_email,
                :start_at,
                :end_at,
                :price
  def initialize(
      id: nil,
      rental_id: nil,
      client_email: nil,
      start_at: nil,
      end_at: nil,
      price: nil
  )
    @id = id
    @rental_id = rental_id
    @client_email = client_email
    @start_at = start_at
    @end_at = end_at
    @price = price
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def set_my_email
    @booking = Booking.new
  end

  def my_bookings
    @bookings = send_booking_index_by_email_request(booking_params)
  end

  def index
    @bookings = send_booking_index_for_all_request
  end

  def show
    response = send_booking_show_request(params)
    @booking = JSON.parse(response.body)
  end

  def new
    @booking = Booking.new
    @bookings = send_booking_index_for_rental_request(rental_params[:rental_id])
  end

  def create
    response = send_create_booking(booking_params)
    if_successful_redirect(
      status: 201,
      response_status: response.status,
      err_messages: JSON.parse(response.body),
      success_text: 'Rental has been booked successfully!',
      success_path: bookings_path,
      failure_path: new_rental_booking_path
    )
  end

  def edit
    response = send_booking_show_request(params)
    @booking = Booking.new(
      start_at: JSON.parse(response.body)['start_at'][0..9].to_date,
      end_at: JSON.parse(response.body)['end_at'][0..9].to_date,
      client_email: JSON.parse(response.body)['client_email']
    )
  end

  def update
    response = send_booking_update_request(booking_params)
    if_successful_redirect(
      status: 200,
      response_status: response.status,
      err_messages: JSON.parse(response.body),
      success_text: 'Booking has been updated successfully!',
      success_path: bookings_path,
      failure_path: edit_rental_booking_path
    )
  end

  def destroy
    response = send_booking_destroy_request(params)
    if_successful_redirect(
      status: 204,
      response_status: response.status,
      err_messages: { 'message' => 'Error: ' + response.status.to_s },
      success_text: 'Booking has been removed successfully!',
      success_path: bookings_path,
      failure_path: bookings_path
    )
  end

  private

  def connect_api
    Faraday.new(url: 'http://localhost:3000') do |c|
      c.use Faraday::Request::UrlEncoded
      c.use Faraday::Response::Logger
      c.use Faraday::Adapter::NetHttp
    end
  end

  # Errol megkerdezni Danit

  def rental_params
    params.permit(:rental_id)
  end

  def booking_params
    booking_p = params.require(:booking)
    # Return this hash
    {
      start_at: join_date(
        booking_p[:'start_at(1i)'],
        booking_p[:'start_at(2i)'],
        booking_p[:'start_at(3i)']
      ),
      end_at: join_date(
        booking_p[:'end_at(1i)'],
        booking_p[:'end_at(2i)'],
        booking_p[:'end_at(3i)']
      ),
      client_email: booking_p[:client_email]
    }
  end

  def join_date(year, month, day)
    [year, month, day].join('-')
  end

  def redirect_for_blank_email
    flash[:danger] = 'Provide a valid e-mail address, please!'
    redirect_to my_email_path
  end

  def redirect_for_email_not_found
    flash[:danger] = 'E-mail address not found!'
    redirect_to my_email_path
  end

  def send_booking_index_by_email_request(booking_params)
    return redirect_for_blank_email if booking_params[:client_email].blank?
    response = connect_api.get '/bookings_by_email', client_email: booking_params[:client_email]
    return redirect_for_email_not_found if response.status == 404
    JSON.parse(response.body)
  end

  def send_booking_index_for_rental_request(rental_id)
    response = connect_api.get '/rentals/' + rental_id.to_s + '/bookings'
    JSON.parse(response.body)
  end

  def send_booking_index_for_all_request
    response = connect_api.get '/bookings'
    JSON.parse(response.body)
  end

  def send_create_booking(booking_params)
    connect_api.post(
      "/rentals/#{rental_params[:rental_id]}/bookings",
      client_email: booking_params[:client_email],
      start_at: booking_params[:start_at],
      end_at: booking_params[:end_at]
    )
  end

  def send_booking_show_request(params)
    connect_api.get "/rentals/#{params[:rental_id]}/bookings/#{params[:id]}"
  end

  def send_booking_update_request(booking_params)
    connect_api.patch(
      "/rentals/#{params[:rental_id]}/bookings/#{params[:id]}",
      start_at: booking_params[:start_at],
      end_at: booking_params[:end_at],
      client_email: booking_params[:client_email]
    )
  end

  def send_booking_destroy_request(params)
    connect_api.delete "/rentals/#{params[:rental_id]}/bookings/#{params[:id]}"
  end

  def if_successful_redirect(options)
    if options[:response_status] == options[:status]
      flash[:success] = options[:success_text]
      redirect_to options[:success_path]
    else
      flash[:danger] = options[:err_messages]['message']
      redirect_to options[:failure_path]
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  
end

app/views/bookings/_index_booking.html.erb
<div>
<h3> Reserved dates </h3>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>From</th>
        <th>To</th>
        <th>By</th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.sort_by{ |element| element['start_at'] }.each do |booking| %>
        <tr>
          <td>          
            <%= booking['start_at'][0..9] %>          
          </td>
          <td>          
            <%= booking['end_at'][0..9]%>          
          </td>
          <td>          
            <%= booking['client_email']%>          
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bookings/_index_bookings.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Reserved by</th>
      <th>From</th>
      <th>To</th>
      <th>Rental ID</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.sort_by{ |element| element['client_email'] }.each do |booking| %>
    <tr>
      <td>          
        <%= booking['client_email'] %>          
      </td>
      <td>          
        <%= booking['start_at'][0..9] %>          
      </td>
      <td>          
        <%= booking['end_at'][0..9]%>          
      </td>
      <td>          
        <%= booking['rental_id']%>          
      </td>
      <td>
        <%= booking['price']%>
      </td>
      <td>
          <div class="pull-right">
            <%= link_to "Show booking", "/rentals/#{booking['rental_id']}/bookings/#{booking['id']}", class: "btn btn-sm btn-primary", method: :get %>
            <%= link_to "Edit", "/rentals/#{booking['rental_id']}/bookings/#{booking['id']}/edit", class: "btn btn-sm btn-primary", method: :get %>
            <%= link_to "Remove", "/rentals/#{booking['rental_id']}/bookings/#{booking['id']}", class: "btn btn-sm btn-primary", method: :delete %>
          </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/_index_bookings_for_rental.html.erb
<div>
<h3> Reserved dates </h3>
  <div class="jumbotron rounded-0">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>From</th>
          <th>To</th>
          <th>By</th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.sort_by{ |element| element['start_at'] }.each do |booking| %>
          <tr>
            <td>          
              <%= booking['start_at'][0..9] %>          
            </td>
            <td>          
              <%= booking['end_at'][0..9]%>          
            </td>
            <td>          
              <%= booking['client_email']%>          
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/bookings/edit.html.erb
<% provide(:title, 'Edit booking') %>
<h1>Edit booking</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@booking, url: rental_booking_path, method: :patch, html: {class: "center"}) do |f| %>

      <div class="row">
      <%= f.label :start_at %>
      <%= f.date_select(:start_at) %>
      <%= f.label :end_at %>
      <%= f.date_select(:end_at) %>
      </div>
      <%= f.label :'e-mail' %>
      <%= f.email_field :client_email, class: 'form-control' %>

      <%= f.submit 'Done', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<% provide(:title, 'All bookings') %>
<div class="jumbotron rounded-0">
<h1>All bookings</h1>
<%= render 'bookings/index_bookings' %>
</div>

app/views/bookings/my_bookings.html.erb
<% provide(:title, 'My bookings') %>
<%= render 'bookings/index_bookings' %>

app/views/bookings/new.html.erb
<% provide(:title, 'Book') %>
<h1>Book!</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@booking, url: rental_bookings_path, html: {class: "center"}) do |f| %>
      <div class="row">
      <%= f.label :start_at %>
      <%= f.date_select(:start_at) %>
      <%= f.label :end_at %>
      <%= f.date_select(:end_at) %>
      </div>
      <%= f.label :'e-mail' %>
      <%= f.email_field :client_email, class: 'form-control' %>

      <%= f.submit 'Book me, please!', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
  <%= render 'bookings/index_bookings_for_rental' %>

app/views/bookings/set_my_email.html.erb
<% provide(:title, 'Provide your e-mail') %>

<h1>Provide your e-mail address</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@booking, url: my_bookings_path, html: {class: "center", method: 'GET'}) do |f| %>

      <%= f.label :'e-mail' %>
      <%= f.email_field :client_email, class: 'form-control' %>

      <%= f.submit 'Go!', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<% provide(:title,"Booking #{@booking['id']}") %>
<div class="jumbotron rounded-0">
<h1>Booking</h1>
<pre>
ID:         <%= @booking['id'] %>
Rental ID:  <%= @booking['rental_id'] %>
Starts at:  <%= @booking['start_at'] %>
Ends at:    <%= @booking['end_at'] %>
Price:      <%= @booking['price'] %>
Created at: <%= @booking['created_at'] %>
Updated at: <%= @booking['updated_at'] %>
</pre>