config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/book_a_rental', to: 'rentals#book_a_rental'
  get '/bookings', to: 'bookings#index'
  get '/my_email', to: 'bookings#set_my_email'
  get '/my_bookings', to: 'bookings#my_bookings'
  resources :rentals do
    resources :bookings, only: %i[new create destroy show edit update]
  end
end

app/models/rental.rb
class Rental
  include ActiveModel::Conversion
  extend  ActiveModel::Naming
  attr_accessor :name,
                :daily_rate
  def initialize(name: nil, daily_rate: nil)
    @name = name
    @daily_rate = daily_rate
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  require 'faraday'
  include RentalsHelper

  def book_a_rental
    @rentals = send_rental_index_request
  end

  def index
    @rentals = send_rental_index_request
  end

  def show
    response = send_rental_show_request(params)
    @rental = JSON.parse(response.body)['rental']
    @bookings = JSON.parse(response.body)['bookings']
  end

  def new
    @rental = Rental.new
  end

  def create
    response = send_create_rental_request(rental_params)
    if_successful_redirect(
      status: 201,
      response_status: response.status,
      err_messages: JSON.parse(response.body),
      success_text: 'Rental has been successfully created!',
      success_path: new_rental_path,
      failure_path: new_rental_path
    )
  end

  def edit
    response = send_rental_show_request(params)
    @rental = Rental.new(
      name: JSON.parse(response.body)['rental']['name'],
      daily_rate: JSON.parse(response.body)['rental']['daily_rate']
    )
  end

  def update
    response = send_rental_update_request(params)
    if_successful_redirect(
      status: 200,
      response_status: response.status,
      err_messages: JSON.parse(response.body),
      success_text: 'Rental has been updated successfully!',
      success_path: rentals_path,
      failure_path: edit_rental_path
    )
  end

  def destroy
    response = send_rental_destroy_request(params)
    if_successful_redirect(
      status: 204,
      response_status: response.status,
      err_messages: { 'message' => 'Error: ' + response.status.to_s },
      success_text: 'Rental has been removed successfully!',
      success_path: rentals_path,
      failure_path: rentals_path
    )
  end

  private

  def connect_api
    Faraday.new(url: 'http://localhost:3000') do |c|
      c.use Faraday::Request::UrlEncoded
      c.use Faraday::Response::Logger
      c.use Faraday::Adapter::NetHttp
    end
  end
  # Az osszes params-t megnezni
  def rental_params
    params.require(:rental).permit(:name, :daily_rate)
  end

  def send_create_rental_request(rental_params)
    connect_api.post(
      '/rentals',
      name: rental_params[:name],
      daily_rate: rental_params[:daily_rate]
    )
  end

  def send_rental_show_request(params)
    connect_api.get "/rentals/#{params[:id]}"
  end

  def send_rental_destroy_request(params)
    connect_api.delete "/rentals/#{params[:id]}"
  end

  def send_rental_update_request(params)
    connect_api.patch(
      "/rentals/#{params[:id]}",
      name: rental_params[:name],
      daily_rate: rental_params[:daily_rate]
    )
  end

  def send_rental_index_request()
    response = connect_api.get '/rentals'
    JSON.parse(response.body)
  end

  def if_successful_redirect(options)
    if options[:response_status] == options[:status]
      flash[:success] = options[:success_text]
      redirect_to options[:success_path]
    else
      flash[:danger] = options[:err_messages]['message']
      redirect_to options[:failure_path]
    end
  end
end

app/helpers/rentals_helper.rb
module RentalsHelper 
end

app/views/rentals/_book_a_rental.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Daily rate</th>
    </tr>
  </thead>
  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td>          
          <%= rental['name'] %>          
        </td>
        <td>          
          <%= rental['daily_rate'].to_s + ' USD' %>          
        </td>
        <td>
          <div class="pull-right">
          <%= link_to "Book me!", '/rentals/' + rental['id'].to_s + '/bookings/new', class: "btn btn-sm btn-primary", method: :get %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rentals/_index_rental.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Daily rate</th>
    </tr>
  </thead>
  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td>          
          <%= rental['name'] %>          
        </td>
        <td>          
          <%= rental['daily_rate'].to_s + ' USD' %>          
        </td>
        <td>
          <div class="pull-right">
            <%= link_to "Show bookings", "/rentals/#{rental['id']}", class: "btn btn-sm btn-primary", method: :get %>
            <%= link_to "Edit", "/rentals/#{rental['id']}/edit", class: "btn btn-sm btn-primary", method: :get %>
            <%= link_to "Remove", "/rentals/#{rental['id']}", class: "btn btn-sm btn-primary", method: :delete %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rentals/_show_rental.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th> E-mail </th>
      <th> Start at </th>
      <th> End at </th>
      <th> Price </th>
      <th> Created at </th>
      <th> Updated at </th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td>          
          <%= booking['client_email'] %>          
        </td>
        <td>          
          <%= booking['start_at'][0..9] %>          
        </td>
        <td>          
          <%= booking['end_at'][0..9] %>          
        </td>
        <td>          
          <%= booking['price'] %>          
        </td>
        <td>          
          <%= booking['created_at'][0..9] %>          
        </td>
        <td>          
          <%= booking['updated_at'][0..9] %>          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rentals/book_a_rental.html.erb
<% provide(:title, 'Book now!') %>
<div class="jumbotron rounded-0">
    <h1>All rentals</h1>
    <%= render 'rentals/book_a_rental' %>
</div>

app/views/rentals/edit.html.erb
<% provide(:title, 'Edit rental') %>
<h1>Edit rental</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@rental, url: rental_path, method: :patch, html: {class: "center"}) do |f| %>

      <%= f.label :rental_name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :daily_rate %>
      <%= f.number_field :daily_rate, class: 'form-control', step: :any %>

      <%= f.submit 'Add', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/rentals/index.html.erb
<% provide(:title, 'All rentals') %>
<div class="jumbotron rounded-0">
  <h1>All rentals</h1>
  <%= render 'rentals/index_rental' %>
</div>

app/views/rentals/new.html.erb
<% provide(:title, 'Add rental') %>
<h1>Add your rental today!</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@rental, url: rentals_path, html: {class: "center"}) do |f| %>

      <%= f.label :rental_name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :daily_rate %>
      <%= f.number_field :daily_rate, class: 'form-control', step: :any %>

      <%= f.submit 'Add', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/rentals/show.html.erb
<% provide(:title, @rental['name']) %>
<div class="jumbotron rounded-0">
<h1>All bookings for <%= @rental['name'] %></h1>
<pre>
ID:         <%= @rental['id'] %>
Name:       <%= @rental['name'] %>
Daily rate: <%= @rental['daily_rate'] %>
Created at: <%= @rental['created_at'] %>
Updated at: <%= @rental['updated_at'] %>
</pre>
<h3>Reserved dates:</h3>
<%= render 'rentals/show_rental' %>
</div>