config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/book_a_rental', to: 'rentals#book_a_rental'
  get '/bookings', to: 'bookings#index'
  get '/my_email', to: 'bookings#set_my_email'
  get '/my_bookings', to: 'bookings#my_bookings'
  resources :rentals do
    resources :bookings, only: %i[new create destroy show edit update]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Mini Bookingsync App by Bence Széplaki
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                                            'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("triangle2.svg", alt: "triangle", size: '30'),
            root_path, id: "triangle2" %>
    <%= link_to "MBA", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Bookings <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Book Now!", book_a_rental_path %></li>
            <li><%= link_to "My bookings", my_email_path %></li>
            <li><%= link_to "All bookings", bookings_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Rentals <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add rental", new_rental_path %></li>
            <li><%= link_to "All rentals", rentals_path %></li>
          </ul>
        </li>
        <li><%= link_to "Help", help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%=render 'layouts/head'%>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
                <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>